version: '3.8'

services:
  db:
    build:
      context: ./server
      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  app:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
    stdin_open: true
    tty: true
    networks:
      - backend
    volumes:
      - file_uploads_volume:/app/uploads
  client:
    depends_on:
      - app
    build:
      context: ./client
    restart: unless-stopped
    ports:
      - 3001:3000
    networks:
      - backend
  nginx:
    depends_on:
      - client
      - app
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - backend
volumes: 
  db:
  file_uploads_volume:
networks:
  backend:
    driver: bridge