version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
    stdin_open: true
    tty: true
    networks:
      - backend
volumes: 
  db:
networks:
  backend:
    driver: bridge