FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/
RUN yarn
COPY . .
RUN yarn build

FROM node:18-alpine

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/uploads ./uploads

CMD ["yarn", "migrate:start:prod"]